apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-datetime-app
spec:
  replicas: 2  #2replicas
  selector:
    matchLabels:
      app: go-datetime-app
  template:
    metadata:
      labels:
        app: go-datetime-app
    spec:
      containers:
      - name: go-datetime-app
        image: prakashravi7483/go-datetime-app:latest  
        ports:
        - containerPort: 8080
